DELETE FROM usbridges.usbridges2016 LIMIT 1

CREATE TABLE STATE_INFO(
	STATE_CODE	CHAR(3),
    STATE_DESC	CHAR(30),
    PRIMARY KEY(STATE_CODE)
);

INSERT INTO STATE_INFO
VALUES ('01', 'Alabama'),
('02', 'Alaska'),
('04', 'Arizona'),
('05', 'Arkansas'),
('06', 'California'),
('08', 'Colorado'),
('09', 'Connecticut'),
('10', 'Delaware'),
('11', 'District of Columbia'),
('12', 'Florida'),
('13', 'Georgia'),
('15', 'Hawaii'),
('16', 'Idaho'),
('17', 'Illinois'),
('18', 'Indiana'),
('19', 'Iowa'),
('20', 'Kansas'),
('21', 'Kentucky'),
('22', 'Louisiana'),
('23', 'Maine'),
('24', 'Maryland'),
('25', 'Massachusetts'),
('26', 'Michigan'),
('27', 'Minnesota'),
('28', 'Mississippi'),
('29', 'Missouri'),
('30', 'Montana'),
('31', 'Nebraska'),
('32', 'Nevada'),
('33', 'New Hampshire'),
('34', 'New Jersey'),
('35', 'New Mexico'),
('36', 'New York'),
('37', 'North Carolina'),
('38', 'North Dakota'),
('39', 'Ohio'),
('40', 'Oklahoma'),
('41', 'Oregon'),
('42', 'Pennsylvania'),
('44', 'Rhode Island'),
('45', 'South Carolina'),
('46', 'South Dakota'),
('47', 'Tennessee'),
('48', 'Texas'),
('49', 'Utah'),
('50', 'Vermont'),
('51', 'Virginia'),
('53', 'Washington'),
('54', 'West Virginia'),
('55', 'Wisconsin'),
('56', 'Wyoming'),
('72', 'Puerto Rico');

ALTER TABLE usbridges.usbridges2016
MODIFY COLUMN OWNER_022 INT

CREATE TABLE OWNER_INFO(
	OWNER_ID	INT,
    OWNER_DESC	CHAR(50),
	PRIMARY KEY(OWNER_ID)
);

INSERT INTO OWNER_INFO
VALUES ('00', 'No Info'),
('01', 'State Highway Agency'),
('02', 'County Highway Agency'),
('03', 'Town or Township Highway Agency'),
('04', 'City or Municipal Highway Agency'),
('11', 'State Park, Forest, or Reservation Agency'),
('12', 'Local Park, Forest, or Reservation Agency'),
('21', 'Other State Agencies'),
('25', 'Other Local Agencies'),
('26', 'Private (other than railroad'),
('27', 'Railroad'),
('31', 'State Toll Authority'),
('32', 'Local Toll Authority'),
('57', 'No Info'),
('58', 'No Info'),
('59', 'No Info'),
('60', 'Other Federal Agencies (not listed below)'),
('61', 'Indian Tribal Government'),
('62', 'Bureau of Indian Affairs'),
('63', 'Bureau of Fish and Wildlife'),
('64', 'U.S. Forest Service'),
('66', 'National Park Service'),
('67', 'Tennessee Valley Authority'),
('68', 'Bureau of Land Management'),
('69', 'Bureau of Reclamation'),
('70', 'Corps of Engineering (Civil)'),
('71', 'Corps of Engineering (Military)'),
('72', 'Air Force'),
('73', 'Navy/Marines'),
('74', 'Army'),
('75', 'NASA'),
('76', 'Metropolitan Washington Airports Service'),
('77', 'No Info'),
('78', 'No Info'),
('79', 'No Info'),
('80', 'Unknown');

CREATE TABLE BRIDGE_DESC(
  STRUCTURE_NUM CHAR(15) NOT NULL,
  STATE_CODE CHAR(3) NOT NULL,
  OWNER_ID INT NOT NULL,
  YEAR_BUILT INT DEFAULT NULL,
  YEAR_RECON INT DEFAULT NULL,
  ADT INT DEFAULT NULL,
  YEAR_ADT INT DEFAULT NULL,
  HIST_SIG INT DEFAULT NULL,
  TOTAL_LENGTH DOUBLE DEFAULT NULL,
  VERT_CLEAR INT DEFAULT NULL,
  ROAD_WIDTH DOUBLE DEFAULT NULL,
  DECK_WIDTH DOUBLE DEFAULT NULL,
  DECK_TYPE INT DEFAULT NULL,
  DESIGN_LOAD INT DEFAULT NULL,
  PRIMARY KEY (STRUCTURE_NUM, STATE_CODE, OWNER_ID),
  FOREIGN KEY (OWNER_ID) REFERENCES OWNER_INFO(OWNER_ID) ON UPDATE CASCADE,
  FOREIGN KEY (STATE_CODE) REFERENCES STATE_INFO(STATE_CODE) ON UPDATE CASCADE
); 

INSERT INTO BRIDGE_DESC
SELECT STRUCTURE_NUMBER_008, STATE_CODE_001, OWNER_022, YEAR_BUILT_027, 
YEAR_RECONSTRUCTED_106, ADT_029, YEAR_ADT_030, HISTORY_037, 
STRUCTURE_LEN_MT_049, VERT_CLR_UND_054B, ROADWAY_WIDTH_MT_051, 
DECK_WIDTH_MT_052, DECK_STRUCTURE_TYPE_107, DESIGN_LOAD_031
FROM usbridges.usbridges2016
WHERE usbridges.usbridges2016.RECORD_TYPE_005A='1';

SELECT STATE_CODE, YEAR_BUILT
FROM (SELECT STATE_CODE, YEAR_BUILT, COUNT(YEAR_BUILT) AS OCCURENCE
    FROM BRIDGE_DESC
    GROUP BY STATE_CODE, YEAR_BUILT
    ORDER BY STATE_CODE, OCCURENCE DESC) AS T
GROUP BY STATE_CODE;

CREATE TABLE SPAN_MATERIAL_INFO(
	MAIN_SPAN_MATERIAL	INT,
    MAIN_SPAN_MATERIAL_DESC	CHAR(50),
    PRIMARY KEY(MAIN_SPAN_MATERIAL)
);

INSERT INTO SPAN_MATERIAL_INFO
VALUES ('1', 'Concrete'),
('2', 'Concrete continuous'),
('3', 'Steel'),
('4', 'Steel Continuous'),
('5', 'Prestressed concrete *'),
('6', 'Prestressed concrete continuous *'),
('7', 'Wood or Timber'),
('8', 'Masonry'),
('9', 'Aluminum, Wrought Iron, or Cast Iron'),
('0', 'Other');

SELECT DISTINCT STRUCTURE_TYPE_043B FROM usbridges.usbridges2016
ORDER BY STRUCTURE_TYPE_043B ASC

SELECT DISTINCT OWNER_022 FROM usbridges.usbridges2016
ORDER BY OWNER_022 ASC

ALTER TABLE usbridges.usbridges2016
MODIFY COLUMN STRUCTURE_TYPE_043B 

SET SQL_SAFE_UPDATES = 0;

UPDATE usbridges.usbridges2016
SET STRUCTURE_TYPE_043B='00'
WHERE STRUCTURE_TYPE_043B != '00' AND
STRUCTURE_TYPE_043B != '01' AND
STRUCTURE_TYPE_043B != '02' AND
STRUCTURE_TYPE_043B != '03' AND
STRUCTURE_TYPE_043B != '04' AND
STRUCTURE_TYPE_043B != '05' AND
STRUCTURE_TYPE_043B != '06' AND
STRUCTURE_TYPE_043B != '07' AND
STRUCTURE_TYPE_043B != '08' AND
STRUCTURE_TYPE_043B != '09' AND
STRUCTURE_TYPE_043B != '10' AND
STRUCTURE_TYPE_043B != '11' AND
STRUCTURE_TYPE_043B != '12' AND
STRUCTURE_TYPE_043B != '13' AND
STRUCTURE_TYPE_043B != '14' AND
STRUCTURE_TYPE_043B != '15' AND
STRUCTURE_TYPE_043B != '16' AND
STRUCTURE_TYPE_043B != '17' AND
STRUCTURE_TYPE_043B != '18' AND
STRUCTURE_TYPE_043B != '19' AND
STRUCTURE_TYPE_043B != '20' AND
STRUCTURE_TYPE_043B != '21' AND
STRUCTURE_TYPE_043B != '22';

SET SQL_SAFE_UPDATES = 1;

CREATE TABLE SPAN_DESIGN_INFO(
	MAIN_SPAN_DESIGN	CHAR(2),
    MAIN_SPAN_DESIGN_DESC	CHAR(50),
    PRIMARY KEY(MAIN_SPAN_DESIGN)
);

INSERT INTO SPAN_DESIGN_INFO
VALUES ('01', 'Slab'),
('02', 'Stringer/Multi-beam or Girder'),
('03', 'Girder and Floorbeam System'),
('04', 'Tee Beam'),
('05', 'Box Beam or Girders - Multiple'),
('06', 'Box Beam or Girders - Single or Spread'),
('07', 'Frame (except frame culverts)'),
('08', 'Orthotropic'),
('09', 'Truss - Deck'),
('10', 'Truss - Thru'),
('11', 'Arch - Deck'),
('12', 'Arch - Thru'),
('13', 'Suspension'),
('14', 'Stayed Girder'),
('15', 'Movable - Lift'),
('16', 'Movable - Bascule'),
('17', 'Movable - Swing'),
('18', 'Tunnel'),
('19', 'Culvert (includes frame culverts)'),
('20', 'Mixed types'),
('21', 'Segmental Box Girder'),
('22', 'Channel Beam'),
('00', 'Other');

CREATE TABLE BRIDGE_SPAN(
	STRUCTURE_NUM CHAR(15) NOT NULL,
	STATE_CODE CHAR(3) NOT NULL,
	OWNER_ID INT NOT NULL,
	MAIN_SPAN_QTY INT DEFAULT NULL,
	LENGTH_MAX_SPAN DOUBLE DEFAULT NULL,
	MAIN_SPAN_MATERIAL INT DEFAULT NULL,
	MAIN_SPAN_DESIGN CHAR(2) DEFAULT NULL,
	PRIMARY KEY (STRUCTURE_NUM, STATE_CODE, OWNER_ID),
	FOREIGN KEY (STATE_CODE) REFERENCES STATE_INFO(STATE_CODE) ON UPDATE CASCADE,
	FOREIGN KEY (OWNER_ID) REFERENCES OWNER_INFO(OWNER_ID) ON UPDATE CASCADE,
    FOREIGN KEY (MAIN_SPAN_MATERIAL) REFERENCES SPAN_MATERIAL_INFO(MAIN_SPAN_MATERIAL) ON UPDATE CASCADE,
	FOREIGN KEY (MAIN_SPAN_DESIGN) REFERENCES SPAN_DESIGN_INFO(MAIN_SPAN_DESIGN) ON UPDATE CASCADE
);

INSERT INTO BRIDGE_SPAN
SELECT STRUCTURE_NUMBER_008, STATE_CODE_001, OWNER_022, 
MAIN_UNIT_SPANS_045, STRUCTURE_LEN_MT_049,
STRUCTURE_KIND_043A, STRUCTURE_TYPE_043B
FROM usbridges.usbridges2016
WHERE usbridges.usbridges2016.RECORD_TYPE_005A='1';

CREATE TABLE BRIDGE_LOCATION (
  STRUCTURE_NUM CHAR(15) NOT NULL,
  STATE_CODE CHAR(3) NOT NULL,
  OWNER_ID INT NOT NULL,
  COUNTY_CODE CHAR(3) DEFAULT NULL,
  PLACE_CODE INT DEFAULT NULL,
  LOCATION CHAR(30) DEFAULT NULL,
  LATITUDE INT DEFAULT NULL,
  LONGITUDE CHAR(9) DEFAULT NULL,
  PRIMARY KEY (STRUCTURE_NUM, STATE_CODE, OWNER_ID),
  FOREIGN KEY (STATE_CODE) REFERENCES STATE_INFO(STATE_CODE) ON UPDATE CASCADE,
  FOREIGN KEY (OWNER_ID) REFERENCES OWNER_INFO(OWNER_ID) ON UPDATE CASCADE
);

INSERT INTO BRIDGE_LOCATION
SELECT STRUCTURE_NUMBER_008, STATE_CODE_001, OWNER_022, 
COUNTY_CODE_003, PLACE_CODE_004, LOCATION_009, LAT_016, LONG_017
FROM usbridges.usbridges2016
WHERE usbridges.usbridges2016.RECORD_TYPE_005A='1';


CREATE TABLE BRIDGE_CONDITION (
  STRUCTURE_NUM CHAR(15) NOT NULL,
  STATE_CODE CHAR(3) NOT NULL,
  OWNER_ID INT NOT NULL,
  INSPECT_DATE INT NOT NULL,
  DECK_COND INT DEFAULT NULL,
  SUPERSTRUC_COND INT DEFAULT NULL,
  SUBSTRUC_COND INT DEFAULT NULL,
  CHANNEL_COND INT DEFAULT NULL,
  CULVERT_COND CHAR(1) DEFAULT NULL,
  PRIMARY KEY (STRUCTURE_NUM, STATE_CODE, OWNER_ID, INSPECT_DATE),
  FOREIGN KEY (STATE_CODE) REFERENCES STATE_INFO(STATE_CODE) ON UPDATE CASCADE,
  FOREIGN KEY (OWNER_ID) REFERENCES OWNER_INFO(OWNER_ID) ON UPDATE CASCADE
);

INSERT INTO BRIDGE_CONDITION
SELECT STRUCTURE_NUMBER_008, STATE_CODE_001, OWNER_022, 
DATE_OF_INSPECT_090, DECK_COND_058, SUPERSTRUCTURE_COND_059,
SUBSTRUCTURE_COND_060, CHANNEL_COND_061, CULVERT_COND_062
FROM usbridges.usbridges2016
WHERE usbridges.usbridges2016.RECORD_TYPE_005A='1';

CREATE TABLE BRIDGE_IMPROVEMENT (
  STRUCTURE_NUM CHAR(15) NOT NULL,
  STATE_CODE CHAR(3) NOT NULL,
  OWNER_ID INT NOT NULL,
  YEAR_IMP CHAR(4) NOT NULL,
  BRIDGE_IMP_COST CHAR(6) DEFAULT NULL,
  ROADWAY_IMP_COST CHAR(6) DEFAULT NULL,
  TOTAL_COST CHAR(6) DEFAULT NULL,
  PRIMARY KEY (STRUCTURE_NUM, STATE_CODE, OWNER_ID, YEAR_IMP),
  FOREIGN KEY (STATE_CODE) REFERENCES STATE_INFO(STATE_CODE) ON UPDATE CASCADE,
  FOREIGN KEY (OWNER_ID) REFERENCES OWNER_INFO(OWNER_ID) ON UPDATE CASCADE
);

INSERT INTO BRIDGE_IMPROVEMENT
SELECT STRUCTURE_NUMBER_008, STATE_CODE_001, OWNER_022, 
YEAR_OF_IMP_097, BRIDGE_IMP_COST_094, 
ROADWAY_IMP_COST_095, TOTAL_IMP_COST_096
FROM usbridges.usbridges2016
WHERE usbridges.usbridges2016.RECORD_TYPE_005A='1';